### ISSUE TITLE
Regarding sampling strategy

### ISSUE THREAD

**Issue by sorobedio** [HSG-AIML/NeurIPS_2022-Generative_Hyper_Representations#1]
In the paper you said that you use the modelzoos 1000 samples per dataset.
but the comand provided in the repo download 5000 samples per architecture.
What is the usefulness of the test split if we are interesting in fitting a generative model that can generate new weights?
I saw in the code you use the training data to fit the kde which is normal to me. but i could not undestand why it does not achieve competitive results as the pretrained weights without training.
another question is does the autoencoder successfully reconstruct the training data? if yes what explained the performance gap between the pretrained and the sampled weights.

thank you

**Comment by kschuerholt** [comment]
Hi, thanks for reaching out! I'm sorry for the delay, I only saw the issue just now. I'll try to respond to each of your questions below.

`In the paper you said that you use the modelzoos 1000 samples per dataset. but the comand provided in the repo download 5000 samples per architecture.`
Yes, that's because we're providing several checkpoints at different epochs of the same model. In this case, it's five subsequent epochs when models have already started to converge. Adding more than just one epoch gives us just a little bit more robustness to the representation learning.

`What is the usefulness of the test split if we are interesting in fitting a generative model that can generate new weights?`
The method has two stages: 1) learning hyper-representations and 2) generating new models. We use the validation and test splits for the first stage, to measure how well the representation learner is able to generalize to models it has not seen yet. 

`I saw in the code you use the training data to fit the kde which is normal to me. but i could not undestand why it does not achieve competitive results as the pretrained weights without training.
another question is does the autoencoder successfully reconstruct the training data? if yes what explained the performance gap between the pretrained and the sampled weights.`
There are several points to mention here. The first is, as you guess, the reconstruction quality of the hyper-representation learner. It depends on the zoo, but is often around 70% R^2. That means that there is some noise introduced by the model. That said, we also explicitly sample new models (which is why generalization beyond the train set matters), and the sampling process also introduces some noise. Our intuition is that samples are abstract combinations of strong patterns of the 'anchor samples', which don't necessarily work perfectly out of the box.

Hope that helps. If you have any other questions, feel free to reach out, e.g. via email: konstantin.schuerholt@unisg.ch.
